language: groovy

service_name: travis-pro
repo_token: 5uRen54fOvg12mRcPFaFtVgGaXFWZe58O

env:
  global:
    - COVERALLS_REPO_TOKEN=5uRen54fOvg12mRcPFaFtVgGaXFWZe58O

install: ./gradlew assemble

script: ./gradlew check

after_success: ./gradlew jacocoTestReport coveralls
